[package]
name = "rls-analysis"
version = "0.5.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]
description = "Library for processing rustc's save-analysis data for the RLS"
license = "Apache-2.0/MIT"
repository = "https://github.com/nrc/rls-analysis"
categories = ["development-tools"]

[dependencies]
rustc-serialize = "0.3"
log = "0.3"
rls-data = "= 0.4.1"
rls-span = "0.4"
derive-new = "0.3"
